// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: with_bg

#ifndef _WITH_BG_UI_H
#define _WITH_BG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label14;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_battery;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Speed;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_temp;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_background_png);    // assets\backGround.png
LV_IMG_DECLARE(ui_img_pentagon_logo_png);    // assets\pentagon logo.png
LV_IMG_DECLARE(ui_img_background_png);    // assets\backGround.png
LV_IMG_DECLARE(
    ui_img_1281517366);    // assets\png-transparent-computer-icons-service-technology-setting-miscellaneous-service-business-thumbnail.png

LV_FONT_DECLARE(ui_font_Font16);
LV_FONT_DECLARE(ui_font_Font24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
